---

- name: config > Log server template
  template:
    src:  config/log_server.j2
    dest: "{{ elao_logio_config_dir }}/log_server.conf"
  register: log_server_conf
  notify:
    - logio-harvester restart
    - logio-server restart

- name: config > Web server template
  template:
    src:  config/web_server.j2
    dest: "{{ elao_logio_config_dir }}/web_server.conf"
  register: web_server_conf
  notify:
    - logio-harvester restart
    - logio-server restart

- name: config > Harvester template
  template:
    src:  config/harvester/base.j2
    dest: "{{ elao_logio_config_dir }}/harvester.conf"
  register: harvester_conf
  notify:
    - logio-harvester restart
    - logio-server restart