---

- name: config > Log server template
  template:
    src:  config/log_server.j2
    dest: "{{ elao_logio_config_dir }}/log_server.conf"
  register: log_server_conf
  notify:
    - log.io-harvester restart
    - log.io-server restart

- name: config > Web server template
  template:
    src:  config/web_server.j2
    dest: "{{ elao_logio_config_dir }}/web_server.conf"
  register: web_server_conf
  notify:
    - log.io-harvester restart
    - log.io-server restart

- name: config > Harvester template
  template:
    src:  config/harvester/base.j2
    dest: "{{ elao_logio_config_dir }}/harvester.conf"
  register: harvester_conf
  notify:
    - log.io-harvester restart
    - log.io-server restart

- name: Force kill log webserver
  shell: "ps aux | grep log.io-server | grep -v grep | awk '{print $2}' | xargs kill -9"
  when: web_server_conf.changed or log_server_conf.changed

- name: Force kill harvester server
  shell: "ps aux | grep log.io-harvester | grep -v grep | awk '{print $2}' | xargs kill -9"
  when: harvester_conf.changed or log_server_conf.changed