---

- name: config > Log server template
  template:
    src:  config/log_server.j2
    dest: "{{ elao_logio_config_dir }}/log_server.conf"
  notify:
    - log.io-harvester restart
    - log.io-server restart

- name: config > Web server template
  template:
    src:  config/web_server.j2
    dest: "{{ elao_logio_config_dir }}/web_server.conf"
  notify:
    - log.io-harvester restart
    - log.io-server restart

- name: config > Harvester template
  template:
    src:  config/harvester/base.j2
    dest: "{{ elao_logio_config_dir }}/harvester.conf"
  notify:
    - log.io-harvester restart
    - log.io-server restart
