---

- name: services > Server init
  template:
    src:   services/logio-server.j2
    dest:  /etc/init.d/logio-server
    owner: root
    mode:  0755
  notify:
    - logio-server restart
    - logio-harvester restart

- name: services > Harvester init
  template:
    src:   services/logio-harvester.j2
    dest:  /etc/init.d/logio-harvester
    owner: root
    mode:  0755
  notify:
    - logio-server restart
    - logio-harvester restart

- name: services > Services
  service:
    name:    "{{ item }}"
    state:   started
    enabled: yes
    daemon-reload: yes
  with_items:
    - logio-server
    - logio-harvester
